AVISource("C:\xyzworkstation\xyz101202\ASSCreatToolVer30\EnglishWordTest\asda.avi", audio=false)AVISource("C:\xyzworkstation\xyz101202\ASSCreatToolVer30\EnglishWordTest\asda.avi", audio=false)
#deinterlace
#crop
#resize
#denoise

LoadPlugin("D:\Program Files\megui\tools\avisynth_plugin\VSFilter.dll")
TextSub("C:\xyzworkstation\xyz101202\ASSCreatToolVer30\EnglishWordTest\EnglishWordComputer.ass", 1)
